<?php 

return [
    [
        'method'=>'GET',
        'resource'=>'post',
        'action'=>'index',
        'controller'=>'PostController', 
        'callback'=>'index', 
    ],
    [
        'method'=>'GET',
        'resource'=>'post',
        'action'=>'show',
        'controller'=>'PostController', 
        'callback'=>'show', 
    ],
    [
        'method'=>'GET',
        'resource'=>'post',
        'action'=>'create',
        'controller'=>'PostController', 
        'callback'=>'create', 
    ],
    [
        'method'=>'POST',
        'resource'=>'post',
        'action'=>'store',
        'controller'=>'PostController', 
        'callback'=>'store', 
    ],
    [
        'method'=>'GET',
        'resource'=>'session',
        'action'=>'create',
        'controller'=>'SessionController', 
        'callback'=>'create', 
    ],
    [
        'method'=>'POST',
        'resource'=>'session',
        'action'=>'store',
        'controller'=>'SessionController', 
        'callback'=>'store', 
    ],
    [
        'method'=>'GET',
        'resource'=>'default',
        'action'=>'default',
        'controller'=>'PostController', 
        'callback'=>'index', 
    ]
];